env :
  production :
  staging :
  development :
    db :
#      net  : "tcp"        # tcp|sock
#      host : "127.0.0.1"  # not required for net:sock
#      port : 3306
      name : "myBusiness"
      user : "root"
      pass : "rootpassword"
    http :
#      port : 8080
